### ISSUE TITLE
Error when creating new pieces / box on tabloro.com

### ISSUE THREAD

**Issue by yattom** [fyyyyy/tabloro#10]
I signed up on tabloro.com.  I got '500 - Oops! Internal server error occured' when tried to create new pieces or box.  

http://www.tabloro.com/pieces/new
http://www.tabloro.com/boxes/new

I'm a new user so I have no asset uploaded yet.   It seems I can play a table someone already created.  I haven't tried running my own server.  I'm sorry that I cannot provide much useful information.

username: yattom
http://www.tabloro.com/users/5e82aa97bba631002c818136

**Comment by telogit** [comment]
Might be the same issue I had posted in the other "tabloro.com offline" issue.

I also got this error yesterday on my machine with a new tabloro.com install.
I was able to create 2 or 3 games, but the next produced an error.

**Comment by fyyyyy** [comment]
Looks like a server side node.js issue

**Comment by telogit** [comment]
This error also occures when you try to create a new table

**Comment by Abry4** [comment]
last comment on facebook is on year 2015... is this still active?

**Comment by telogit** [comment]
yes, it is ;-)

**Comment by telogit** [comment]
On my local machine I get the 500 error as well.
I tried to create a game piece and ended up with the error.

Here the stack trace:
`
500 - Oops! Internal server error occured
      TypeError: tags.split is not a function
    at model.setTags (/home/server/Downloads/tabloro-master/app/models/piece.js:31:15)
    at SchemaArray.SchemaType._applySetters (/home/server/Downloads/tabloro-master/node_modules/mongoose/lib/schematype.js:938:22)
    at SchemaArray.SchemaType.applySetters (/home/server/Downloads/tabloro-master/node_modules/mongoose/lib/schematype.js:962:16)
    at SchemaArray.SchemaType.getDefault (/home/server/Downloads/tabloro-master/node_modules/mongoose/lib/schematype.js:916:25)
    at $__applyDefaults (/home/server/Downloads/tabloro-master/node_modules/mongoose/lib/document.js:375:22)
    at model.Document (/home/server/Downloads/tabloro-master/node_modules/mongoose/lib/document.js:123:5)
    at model.Model (/home/server/Downloads/tabloro-master/node_modules/mongoose/lib/model.js:93:12)
    at new model (/home/server/Downloads/tabloro-master/node_modules/mongoose/lib/model.js:4421:15)
    at exports.new (/home/server/Downloads/tabloro-master/app/controllers/pieces.js:72:16)
    at Layer.handle [as handle_request] (/home/server/Downloads/tabloro-master/node_modules/express/lib/router/layer.js:76:5)
    at next (/home/server/Downloads/tabloro-master/node_modules/express/lib/router/route.js:100:13)
    at exports.requiresLogin (/home/server/Downloads/tabloro-master/config/middlewares/authorization.js:8:37)
    at Layer.handle [as handle_request] (/home/server/Downloads/tabloro-master/node_modules/express/lib/router/layer.js:76:5)
    at next (/home/server/Downloads/tabloro-master/node_modules/express/lib/router/route.js:100:13)
    at Route.dispatch (/home/server/Downloads/tabloro-master/node_modules/express/lib/router/route.js:81:3)
    at Layer.handle [as handle_request] (/home/server/Downloads/tabloro-master/node_modules/express/lib/router/layer.js:76:5)`

**Comment by fyyyyy** [comment]
seems to be related to s3 storage.

**Comment by fyyyyy** [comment]
fix pushed

**Comment by fyyyyy** [comment]
Seems fixed, i can create tables on tabloro.com

**Comment by fyyyyy** [comment]
Oh man, too many changes in the 13 node version. Interfaces in mongoose changed a lot, this will take more time to figure out. Probably easier to make it work under node 0.11

**Comment by fyyyyy** [comment]
Ok, had to fix some more stuff, using now node version 5 seems to be the best compromise.
Hopefully nothing else breaks. New tables can be created.

**Comment by fyyyyy** [comment]
talking about development branch btw. which is currently also deployed.
Havent update master yet

**Comment by telogit** [comment]
Great, I will check it out.
Anything that needs to be taken into account? 
Or just npm install etc?

**Comment by fyyyyy** [comment]
use the right node version before install, i think its 5.11 but check package.json

**Comment by JJones780** [comment]
I've pushed some changes to my simpleserver branch that might be useful in master including:

EDIT: I'll look at putting these into their own branch for merging.. no time right now.

Server:
- Remove unique users from tables schema. Existing mongo: db.tables.dropIndex('users_1').  ( I wasn't able to make multiple tables for a setup ). 
Client:
- Limit pinch zoom on tablets ( it was inverting, going extreme )
- Raise piece controls above piece for easier access of smaller pieces.
- allow rotate of multiple piece selection,
- fix: select 1 by dragging box was showing controls for multiple.
-fix: client not seeing rotateBy piece setting.

Be warned, there are some other changes you DO NOT want in master ( i.e. skype  changes ).

On my maybe TODO radar:
Need to store tile's "z" position and sync with other users.
Ability to rearrange/organize pieces held in hand - multiple columns?
Problem with moving view while dragging item(s) with mouse.
change Rotate By - let user enter rotation steps i.e.  360 divisor,  instead of angle ?( so setting 4 would equate to 360/4 = 90degrees ).

**Comment by fyyyyy** [comment]
Master branch is now on autodeploy, so any MR's going into master are deployed to tabloro.com
